# Generated by Django 4.0.3 on 2022-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('PT', 'Patient'), ('HP', 'HealthcareProfessional'), ('HS', 'Hospital'), ('PH', 'Pharmacy'), ('IF', 'InsuranceFirm')], default='PT', max_length=50)),
                ('address', models.CharField(default='none', max_length=300)),
                ('contact', models.CharField(default='none', max_length=15)),
                ('vAadhar', models.CharField(default='none', max_length=50)),
                ('healthLicense', models.CharField(default='none', max_length=200)),
                ('description', models.CharField(default='none', max_length=500)),
                ('location', models.CharField(default='none', max_length=200)),
                ('image1Path', models.CharField(default='none', max_length=100)),
                ('image2Path', models.CharField(default='none', max_length=100)),
                ('status', models.CharField(choices=[('AU', 'Authenticated'), ('NA', 'NotAuthenticated'), ('RM', 'Removed')], default='NA', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
