# Generated by Django 4.0.3 on 2022-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1Path',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2Path',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='vAadhar',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
