# Generated by Django 4.0.3 on 2022-11-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='userID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingdocumentrequests',
            name='userID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sharerecords',
            name='userID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadrecords',
            name='userID',
            field=models.CharField(max_length=100),
        ),
    ]
