# Generated by Django 4.0.3 on 2022-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerecords',
            name='fileHash',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uploadrecords',
            name='fileHash',
            field=models.CharField(max_length=1000),
        ),
    ]
