# Generated by Django 4.1.2 on 2022-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('receiverID', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('docType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('receiverID', models.CharField(max_length=30)),
                ('docLink', models.CharField(max_length=100)),
                ('docType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UploadRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('docLink', models.CharField(max_length=100)),
                ('docType', models.CharField(max_length=30)),
            ],
        ),
    ]
