# Generated by Django 4.0.3 on 2022-11-27 21:39

from django.db import migrations, models
import patient_mgmt_backend.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1Path',
            field=models.FileField(blank=True, default='mediafiles/post_images/default.txt', null=True, upload_to='post_images', validators=[patient_mgmt_backend.validators.validate_file_size, patient_mgmt_backend.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2Path',
            field=models.FileField(blank=True, default='mediafiles/post_images/default.txt', null=True, upload_to='post_images', validators=[patient_mgmt_backend.validators.validate_file_size, patient_mgmt_backend.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='user',
            name='vAadhar',
            field=models.FileField(blank=True, default='mediafiles/post_images/default.txt', null=True, upload_to='post_images', validators=[patient_mgmt_backend.validators.validate_file_size, patient_mgmt_backend.validators.validate_file_extension]),
        ),
    ]
