# Generated by Django 4.1.2 on 2022-10-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0002_claimrecords_sharerecords_uploadrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('receiverID', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('PT', 'Patient'), ('HP', 'HealthcareProfessional'), ('HS', 'Hospital'), ('PH', 'Pharmacy'), ('IF', 'InsuranceFirm')], default='PT', max_length=50)),
                ('address', models.CharField(default='none', max_length=300)),
                ('contact', models.CharField(default='none', max_length=15)),
                ('vAadhar', models.CharField(default='none', max_length=50)),
                ('healthLicense', models.CharField(default='none', max_length=200)),
                ('description', models.CharField(default='none', max_length=500)),
                ('location', models.CharField(default='none', max_length=200)),
                ('image1Path', models.CharField(default='none', max_length=100)),
                ('image2Path', models.CharField(default='none', max_length=100)),
                ('status', models.CharField(choices=[('AU', 'Authenticated'), ('NA', 'NotAuthenticated'), ('RM', 'Removed')], default='NA', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ClaimRecords',
        ),
    ]
