# Generated by Django 4.0.3 on 2022-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0002_paymentrecords_react_sharerecords_uploadrecords_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareRecords',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
        migrations.AlterField(
            model_name='uploadrecords',
            name='docLink',
            field=models.CharField(max_length=5000),
        ),
    ]
