# Generated by Django 4.0.3 on 2022-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptableregistration',
            name='userEmail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecords',
            name='payerID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrecords',
            name='receiverEmail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingdocumentrequests',
            name='receiverEmail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharerecords',
            name='receiverEmail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharerecords',
            name='reportID',
            field=models.CharField(max_length=100),
        ),
    ]
