# Generated by Django 4.0.3 on 2022-11-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0003_alter_pendingdocumentrequests_requestcompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdocumentrequests',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingdocumentrequests',
            name='requestCompleted',
            field=models.CharField(max_length=30),
        ),
    ]
