# Generated by Django 4.1.2 on 2022-10-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0003_paymentrecords_usertable_delete_claimrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(default='PT', max_length=50),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='status',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
