# Generated by Django 4.1.3 on 2022-11-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0004_alter_usertable_role_alter_usertable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecords',
            name='docLink',
            field=models.ImageField(upload_to='uploaded_files'),
        ),
    ]
