# Generated by Django 4.0.3 on 2022-11-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0004_sharerecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRecords',
        ),
    ]
