# Generated by Django 4.0.3 on 2022-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0005_delete_paymentrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payerID', models.CharField(max_length=30)),
                ('receiverEmail', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
