# Generated by Django 4.0.3 on 2022-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0007_otptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOtpVerified',
            field=models.CharField(choices=[('No', 'NotVerified'), ('Yes', 'Verified')], default='No', max_length=10),
        ),
    ]
