# Generated by Django 4.0.3 on 2022-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0009_otptableregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default='', max_length=300),
        ),
    ]
