# Generated by Django 4.0.3 on 2022-11-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0010_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isOtpVerified',
        ),
    ]
