# Generated by Django 4.0.3 on 2022-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0011_remove_user_isotpverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDocumentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('receiverEmail', models.CharField(max_length=50)),
                ('docType', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('requestCompleted', models.CharField(max_length=30)),
            ],
        ),
    ]
