# Generated by Django 4.0.3 on 2022-11-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0016_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generated_file_name', models.CharField(max_length=500)),
                ('workflow_id', models.PositiveIntegerField()),
                ('step_id', models.PositiveIntegerField()),
                ('owner_id', models.CharField(max_length=50)),
                ('datetime_uploaded', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(default='not_verified', max_length=100)),
                ('type', models.CharField(default='user_admin', max_length=100)),
            ],
        ),
    ]
