# Generated by Django 4.0.3 on 2022-11-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0017_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
    ]
