# Generated by Django 4.0.3 on 2022-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0018_remove_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='datetime_uploaded',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='step_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='verification_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='workflow_id',
            field=models.CharField(max_length=100),
        ),
    ]
