# Generated by Django 4.0.3 on 2022-11-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0019_alter_document_datetime_uploaded_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
