# Generated by Django 4.0.3 on 2022-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0020_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerecords',
            name='docLink',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadrecords',
            name='docLink',
            field=models.CharField(max_length=200),
        ),
    ]
