# Generated by Django 4.0.3 on 2022-11-26 13:03

from django.db import migrations, models
import patient_mgmt_backend.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt_backend', '0023_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='post_images', validators=[patient_mgmt_backend.validators.validate_file_size]),
        ),
    ]
